FROM gabesullice/drocker-drupal-8:8.1

# Install xdebug
RUN pecl install xdebug-beta && docker-php-ext-enable xdebug
COPY .data/php/php.ini /usr/local/etc/php/php.ini

RUN ln -sf /var/www/files /var/www/html/sites/default/files
RUN ln -sf /var/www/settings/settings.local.php /var/www/html/sites/default/settings.local.php

COPY ./public_html/sites/default/settings.php /var/www/html/sites/default/settings.php

COPY ./public_html/themes /var/www/html/themes
COPY ./public_html/modules /var/www/html/modules

VOLUME /var/www/html
VOLUME /var/www/files
