#!/bin/bash

set -e

script_name=$(basename $0)

# Define container and networking defaults
project_name=$(basename $PWD | sed 's/-//g' | sed 's/_//g')
drupal_cli_image=gabesullice/drocker-drupal-cli
mysql_container=$(printf "%b%b" $project_name "_mysql_1")
drupal_container=$(printf "%b%b" $project_name "_drupal_1")
drocker_env_files=""

main () {
  local subcmd=$1
  local args=${@:2}

  if [ $# -lt 1 ]; then
    error "You must provide at least one subcommand. See \`$script_name help\` for more info."
    subcmd="help"
  fi

  if [ "$subcmd" = "help" ]; then
    local commands=( "init" "scaffold" "bootstrap" "connect" "down" "build" "refresh" "drush" "errors" "install-prepare" "permissions" "shell" "sqlc" "sql-import" "up" )
    printf "Possible subcmds are:\n"
    printf "\t%s\n" "${commands[@]}"
    printf "For more information about these commands, see %b [SUBCMD] help.\n" $script_name
    exit 1
  fi

  configure

  $subcmd $args
}

remote () {
  if [ "$1" = "help" ]; then
    printf "Usage: %b %b \e[4mHOST\e[0m [...command]\n" $script_name $FUNCNAME
    printf "Executes the drocker command on the remote host provided.\n"
    printf "Please note that interactive commands like \`connect\` and \`sqlc\` do not work in remote mode.\n"
    printf "Example: %b %b sshuser@some.domain drush uli\n" $script_name $FUNCNAME
    exit 0
  fi

  local remote_host=$1

  ssh -A $remote_host /bin/bash -s ${@:2} < $0
}

up () {
  if [ "$1" = "help" ]; then
    printf "Usage: %b %b\n" $script_name $FUNCNAME
    printf "Alias for \`docker-compose up -d\`\n"
    exit 0
  fi

  log "docker-compose -p $project_name up -d"
  docker-compose -p $project_name up -d
}

down () {
  if [ "$1" = "help" ]; then
    printf "Usage: %b %b\n" $script_name $FUNCNAME
    printf "Alias for \`docker-compose down\`\n"
    exit 0
  fi

  log "docker-compose -p $project_name down"
  docker-compose -p $project_name down
}

build () {
  if [ "$1" = "help" ]; then
    printf "Usage: %b %b\n" $script_name $FUNCNAME
    printf "Alias for \`docker-compose build\`\n"
    exit 0
  fi

  log "docker-compose -p $project_name build"
  docker-compose -p $project_name build
}

refresh () {
  if [ "$1" = "help" ]; then
    printf "Usage: %b %b\n" $script_name $FUNCNAME
    printf "Alias for \`docker-compose down && docker-compose build && docker-compose up\`\n"
    exit 0
  fi

  down && build && up
}

drush () {
  local args=${@:1}

  if [ "$1" = "help" ]; then
    printf "Usage: %b %b [...drush args]\n" $script_name $FUNCNAME
    printf "Use as you would regular drush. This command simply prefixes the drush command with the appropriate docker command.\n"
    exit 0
  fi

  log "docker run --user=$(id -u) --rm -i $drocker_env_files --volumes-from=$drupal_container --net=$docker_network $drupal_cli_image drush $args"

  docker run --user=$(id -u) --rm -i $drocker_env_files --volumes-from=$drupal_container --net=$docker_network $drupal_cli_image drush $args
}

errors () {
  local args=${@:1}

  if [ "$1" = "help" ]; then
    printf "Usage: %b %b\n" $script_name $FUNCNAME
    printf "Streams drupal watchdog errors. Same as \`drush watchdog-show --tail\`.\n"
    exit 0
  fi

  log "docker run --user=$(id -u) --rm -it $drocker_env_files --volumes-from=$drupal_container --net=$docker_network $drupal_cli_image /bin/ash -c 'drush ws --tail'"

  docker run --user=$(id -u) --rm -it $drocker_env_files --volumes-from=$drupal_container --net=$docker_network $drupal_cli_image /bin/ash -c 'drush ws --tail'
}

sqlc () {
  local args=${@:1}

  if [ "$1" = "help" ]; then
    printf "Usage: %b %b\n" $script_name $FUNCNAME
    printf "Use as you would drush sqlc.\n"
    exit 0
  fi

  log "docker exec --user=$(id -u) -it $mysql_container /bin/sh -c 'mysql -A -u \$MYSQL_USER -p\$MYSQL_PASSWORD \$MYSQL_DATABASE'"

  docker exec --user=$(id -u) -it $mysql_container /bin/sh -c 'mysql -A -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE'
}

shell () {
  local args=${@:1}

  if [ "$1" = "help" ]; then
    printf "Usage: %b %b [shell command]\n" $script_name $FUNCNAME
    printf "Run arbitrary commands in the drocker container. This command simply prefixes the your shell command with the appropriate docker command. You will need to escape any quotes with a \\.\n"
    exit 0
  fi

  log "docker run --rm -i $drocker_env_files --volumes-from=$drupal_container --net=$docker_network $drupal_cli_image /bin/ash -c '$args'"

  docker run --rm -i $drocker_env_files --volumes-from=$drupal_container --net=$docker_network $drupal_cli_image /bin/ash -c "$args"
}

sql-import () {
  if [ "$1" = "help" ]; then
    printf "Usage: %b %b \e[4mFILE\e[0m\n" $script_name $FUNCNAME
    printf "Imports the given SQL file into the running instance of drocker. Must not be gzipped.\n"
    exit 0
  fi

  log "docker run --rm -i $drocker_env_files --volumes-from=$drupal_container --net=$docker_network $drupal_cli_image drush sql-cli < $1"

  docker run --rm -i $drocker_env_files --volumes-from=$drupal_container --net=$docker_network $drupal_cli_image drush sql-cli < $1
}

install-prepare () {
  local args=${@:1}

  if [ "$1" = "help" ]; then
    printf "Usage: %b %b\n" $script_name $FUNCNAME
    printf "This will prepare your container for installing Drupal. You should run \`$script_name permissions\` after your installation is complete."
    exit 0
  fi

  permissions \
    && sudo docker run --rm -i -u root $drocker_env_files --volumes-from=$drupal_container --net=$docker_network $drupal_cli_image /bin/ash -c "\
    ln -sf /var/www/files /var/www/html/sites/default/files \
    && settingsFile=/var/www/html/sites/default/settings.php \
      && if [[ ! -e \$settingsFile ]]; then \
        cp /var/www/html/sites/default/default.settings.php \$settingsFile; \
      fi\
      && if [[ -e \$settingsFile ]]; then \
        chown $(id -u):www-data \$settingsFile; \
        chmod 664 \$settingsFile; \
      fi"

  warning "Do not forget to run \`$script_name permissions\` once your install is complete."
}

permissions () {
  local args=${@:1}

  if [ "$1" = "help" ]; then
    printf "Usage: %b %b\n" $script_name $FUNCNAME
    printf "This will set permissions correctly for php-fpm and nginx within the docker container."
    exit 0
  fi

  sudo docker run --rm -i -u root $drocker_env_files --volumes-from=$drupal_container --net=$docker_network $drupal_cli_image /bin/ash -c "\
    mkdir -p /var/www/html /var/www/private /var/www/settings /var/www/files /var/www/config \
    && chown -R $(id -u):www-data \
      /var/www/html \
      /var/www/private \
      /var/www/settings \
      /var/www/files \
      /var/www/config \
      /var/www/html/modules \
      /var/www/html/vendor \
      /var/www/html/composer.json \
      /var/www/html/composer.lock \
    && find /var/www/html /var/www/settings -type d -exec chmod 755 {} \+ \
    && find /var/www/html /var/www/settings -type f -exec chmod 744 {} \+ \
    && find /var/www/files /var/www/private /var/www/config -type d -exec chmod 775 {} \+ \
    && find /var/www/files /var/www/private /var/www/config -type f -exec chmod 764 {} \+ \
    && settingsFile=/var/www/html/sites/default/settings.php && if [[ -e \$settingsFile ]]; then chmod 644 \$settingsFile; fi\
    && settingsFile=/var/www/html/sites/default/services.yml && if [[ -e \$settingsFile ]]; then chmod 644 \$settingsFile; fi\
    && settingsFile=/var/www/html/sites/default/settings.local.php && if [[ -e \$settingsFile ]]; then chmod 644 \$settingsFile; fi\
    && settingsFile=/var/www/html/sites/default/local-settings.inc && if [[ -e \$settingsFile ]]; then chmod 644 \$settingsFile; fi"
}

connect () {
  if [ "$1" = "help" ]; then
    printf "Usage: %b %b\n" $script_name $FUNCNAME
    printf "Starts an SSH session in docker drush container.\n"
    exit 0
  fi

  log "docker run --rm -it $drocker_env_files --volumes-from=$drupal_container --net=$docker_network $drupal_cli_image /bin/ash -l"

  docker run --rm -it $drocker_env_files --volumes-from=$drupal_container --net=$docker_network $drupal_cli_image /bin/ash -l
}

configure () {
  local arg=$1

  if [ "$1" = "help" ]; then
    printf "Usage: %b %b [\e[4mENVIRONMENT FILE\e[0m]\n" $script_name $FUNCNAME
    printf "Overrides drocker's configuration with the environment variables in \e[4mENVIRONMENT FILE\e[0m. If no argument is passed, the default is ./.drocker.\n"
    exit 0
  fi

  local config_file=$(find_config)

  if [[ -f $config_file ]]; then
    source $config_file
    project_name=${DROCKER_PROJECT_NAME:=$project_name}
    drupal_cli_image=${DROCKER_CLI_IMAGE:=$drupal_cli_image}
    mysql_container=${DROCKER_MYSQL_CONTAINER:=$mysql_container}
    drupal_container=${DROCKER_DRUPAL_CONTAINER:=$drupal_container}
    docker_network=${DROCKER_DOCKER_NETWORK:=`docker inspect -f "{{range .NetworkSettings.Networks}}{{.NetworkID}}{{end}}" $mysql_container | head -c 7`}
    drocker_env_files=${DROCKER_ENV_FILES:=$drocker_env_files}
  fi

}

init () {
  if [ "$1" = "help" ]; then
    printf "Usage: %b %b\n" $script_name $FUNCNAME
    printf "Starts a new drocker project from scratch."
    exit 0
  fi

  scaffold
  build
  bootstrap
  drush si
  permissions
}

scaffold () {
  if [ "$1" = "help" ]; then
    printf "Usage: %b %b\n" $script_name $FUNCNAME
    printf "Scaffolds a new drocker project from scratch without bootstrapping or installing anything."
    exit 0
  fi

  curl -sS -Lo ./install.sh https://raw.githubusercontent.com/gabesullice/drocker/master/bootstrap/install.sh \
    && chmod u+x ./install.sh \
    && ./install.sh \
    && rm ./install.sh
}

bootstrap () {
  if [ "$1" = "help" ]; then
    printf "Usage: %b %b\n" $script_name $FUNCNAME
    printf "Bootstraps a new drocker project after the scaffolding has been created."
    exit 0
  fi

  local drupal_root=./docroot
  local default_dir=$drupal_root/sites/default

  if [[ ! -e ./docroot ]]; then $(which drush) dl --drupal-project-rename=docroot drupal; fi
  if [[ ! -e $default_dir/settings.php ]]; then
    cp $default_dir/default.settings.php $default_dir/settings.php
    cat << EOF >> $default_dir/settings.php
if (file_exists(__DIR__ . '/settings.local.php')) {                           
  include __DIR__ . '/settings.local.php';                                    
}
EOF
  fi

  up
  install-prepare
}

find_config () {
  local cwd=$(pwd)
  local config_file=""

  while [[ $cwd != "/" ]]; do
    if [[ -e $cwd/.drocker ]]; then
      config_file=$cwd/.drocker
      break
    fi
    cwd=$(dirname $cwd)
  done;

  if [[ -z $config_file ]]; then
    error "Could not locate a .drocker config file. Falling back to defaults..."
    exit 1
  else
    echo $config_file
  fi
}

log () {
  (>&2 echo "$1")
}

error () {
  (>&2 echo -e "\e[31m$1\e[0m")
}

warning () {
  (>&2 echo -e "\e[33m$1\e[0m")
}

main $@
