#!/bin/bash

set -e

script_name=$0

drocker_root=${DROCKER_ROOT:=$(pwd)}
drocker_vm_ip=${DROCKER_VM_IP:=192.168.33.33}
drocker_mount_dir=${DROCKER_MOUNT_DIR:=$HOME/drocker}

main () {
  local subcmd=$1
  local args=${@:2}

  if [ $# -lt 1 ]; then
    printf "You must provide at least one subcommand.\n"
    subcmd="help"
  fi

  if [ "$subcmd" = "help" ]; then
    local commands=( "init" "up" "down" "ssh" )
    printf "Possible subcmds are:\n"
    printf "\t%s\n" "${commands[@]}"
    printf "For more information about these commands, see %b [SUBCMD] help.\n" $script_name
    exit 1
  fi

  $subcmd $args
}

init () {
  if [ "$1" = "help" ]; then
    printf "Usage: %b %b\n" $script_name $FUNCNAME
    printf "Brings up the drocker machine for the first time and creates a local directory to mount the drocker www directory into.\n"
    exit 0
  fi

  log "mkdir -p $drocker_mount_dir"
  log "pushd $drocker_root/vagrant && vagrant up && popd"

  mkdir -p $drocker_mount_dir
  pushd $drocker_root/vagrant && vagrant up && popd
}

up () {
  if [ "$1" = "help" ]; then
    printf "Usage: %b %b\n" $script_name $FUNCNAME
    printf "Brings up or reloads the drocker vagrant machine, then mounts the shared directory.\n"
    exit 0
  fi

  log "pushd $drocker_root/vagrant && vagrant reload && popd"
  log "sudo mount -t nfs -o resvport,rw $drocker_vm_ip:/var/www $drocker_mount_dir"

  pushd $drocker_root/vagrant && vagrant reload && popd
  sudo mount -t nfs -o resvport,rw $drocker_vm_ip:/var/www $drocker_mount_dir
}

down () {
  if [ "$1" = "help" ]; then
    printf "Usage: %b %b\n" $script_name $FUNCNAME
    printf "Suspends the drocker vagrant machine and unmounts the shared directory.\n"
    exit 0
  fi

  log "pushd $drocker_root/vagrant && vagrant suspend && popd"
  log "sudo umount -l $drocker_mount_dir"

  pushd $drocker_root/vagrant && vagrant suspend && popd
  sudo umount -l $drocker_mount_dir
}

ssh () {
  if [ "$1" = "help" ]; then
    printf "Usage: %b %b\n" $script_name $FUNCNAME
    printf "Starts an SSH session in the drocker vagrant machine.\n"
    exit 0
  fi

  log "pushd $drocker_root/vagrant && vagrant ssh -c 'cd /var/www && /bin/bash -l' && popd"

  pushd $drocker_root/vagrant && vagrant ssh -c 'cd /var/www && /bin/bash -l' && popd
}
